service_llm_provider: gemini-vertex
service_model_name: gemini-1.5-flash-001
rate_limit_per_minute: 1000
prompt_tmpl_path: config/prompts.toml
service_llm_gen_config_path: config/llama3_1b/eval/gemini_gen_configs.yaml

lm_response_ds_id: llama-duo/llama3-1b-classification-locallm-response
lm_response_ds_split: llama3_1b_classification_gpt4o_100k

eval_data_preprocess_bs: 16
eval_repeat: 10

rate_limit_on: false
eval_workers: 10

avg_similarity_threshold: 90.0
avg_precision_threshold: 90.0

push_eval_to_hf_hub: true
eval_ds_id: llama-duo/llama3-1b-classification-eval-by-gemini15flash
eval_ds_split: llama3_1b_classification_gpt4o_100k_by_gemini1_5flash
eval_ds_append: true

# 
# 
# 
# 
# 
# 
# 
# 
# 