ft_model_id: llama-duo/llama3-8b-classification-gpt4o-100k
ft_model_revision: main
ft_model_config_path: config/llama3.1_8b/llama3.1_8b_classification_100k.yaml
ft_model_gen_config_path: config/llama3.1_8b/ft_gen_configs.yaml
user_delimiter: user
model_delimiter: assistant

test_ds_id: llama-duo/coverage_dataset
test_ds_split: test_classify

batch_infer_data_preprocess_bs: 16
inference_bs: 8
repeat: 4

push_lm_responses_to_hf_hub: true
lm_response_ds_id: llama-duo/llama3-8b-classification-locallm-response
lm_response_ds_split: llama3_8b_classification_gpt4o_100k
lm-response-append: false
