ft_model_id: chansung/coding_llamaduo_60k_v0.2
ft_model_revision: main
ft_model_config_path: config/sample_config.yaml

test_ds_id: sayakpaul/no_robots_only_coding
test_ds_split: test_sft

batch_infer_data_preprocess_bs: 16
inference_bs: 8
repeat: 4

push_lm_responses_to_hf_hub: true
lm_response_ds_id: chansung/llamaduo-responses
lm_response_ds_split: batch_infer
lm-response-append: false