service_model_name: gemini-1.0-pro
rate_limit_per_minute: 60
prompt_tmpl_path: config/prompts.toml

reference_ds_id: sayakpaul/no_robots_only_coding
reference_ds_split: train_sft
num_samples: 30
seed: 2024
topic: Coding

prompt_tmpl_path: config/prompts.toml

gen_workers: 4

push_synth_ds_to_hf_hub: true
synth_ds_id: chansung/synth_ds_test5
synth_ds_split: test
synth_ds_append: true